import { esc, icon } from "./helpers.mjs";
const NAV = [["/", "Home"], ["/builder/", "AI Builder"], ["/ideas/", "Idea Lab"], ["/board/", "Devour Board"], ["/journal/", "Tasting Journal"]];
function active(path, href) { return href === "/" ? path === "/" : path === href || path.startsWith(href); }
function brand() { return `<a class="brand" href="/" aria-label="BurgerForge AI home"><span class="brand-mark" aria-hidden="true">${icon("burger")}</span><span><strong>BurgerForge</strong><small>AI kitchen lab</small></span></a>`; }
function header(path) {
  return `<header class="site-header"><div class="shell header-inner">${brand()}<button class="icon-button menu-button" type="button" data-menu-toggle aria-expanded="false" aria-controls="primary-nav" aria-label="Open navigation">${icon("menu")}</button><nav class="primary-nav" id="primary-nav" data-primary-nav aria-label="Primary">${NAV.map(([href,label])=>`<a href="${href}"${active(path,href)?' aria-current="page"':''}>${label}</a>`).join("")}<a class="nav-secondary" href="/about/">About</a></nav><button class="icon-button" type="button" data-theme-toggle aria-label="Change colour theme">${icon("spark")}</button></div></header>`;
}
function footer() {
  return `<footer class="site-footer"><div class="shell footer-grid"><div>${brand()}<p>Build creative burger concepts, choose what belongs on your board, and keep a private tasting journal.</p></div><div><h2>Create</h2><a href="/builder/">AI Burger Builder</a><a href="/ideas/">Curated ideas</a><a href="/board/">Devour Board</a></div><div><h2>Learn</h2><a href="/about/">Architecture</a><a href="/safety/">Food & AI safety</a><a href="/privacy/">Privacy</a></div><div><h2>Project</h2><a href="/.well-known/security.txt">Security</a><a href="/offline/">Offline mode</a></div></div><div class="shell footer-bottom"><span>© 2026 BurgerForge AI.</span><span>Fictional portfolio demonstration. No order is placed and no dietary claim is verified.</span></div></footer>`;
}
function resolveOrigin() {
  const explicit = (process.env.SITE_URL || "").replace(/\/$/, "");
  if (explicit) return explicit;
  const prod = (process.env.VERCEL_PROJECT_PRODUCTION_URL || "").replace(/^https?:\/\//, "").replace(/\/$/, "");
  return prod ? `https://${prod}` : "";
}
export function renderDocument({ title, description, path, main, scripts = [], bodyClass = "", robots = "noindex,nofollow" }) {
  const origin = resolveOrigin();
  const fullTitle = path === "/" ? title : `${title} · BurgerForge AI`;
  const canonical = origin ? `${origin}${path}` : "";
  const social = origin ? `${origin}/assets/images/social-card.png` : "";
  return `<!doctype html><html lang="en" data-theme="system"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(fullTitle)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${esc(robots)}"><meta name="application-name" content="BurgerForge AI"><meta name="theme-color" content="#f0502f"><meta name="color-scheme" content="light dark">${canonical?`<link rel="canonical" href="${canonical}"><meta property="og:url" content="${canonical}">`:""}<meta property="og:type" content="website"><meta property="og:site_name" content="BurgerForge AI"><meta property="og:title" content="${esc(fullTitle)}"><meta property="og:description" content="${esc(description)}">${social?`<meta property="og:image" content="${social}"><meta name="twitter:image" content="${social}">`:""}<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(fullTitle)}"><meta name="twitter:description" content="${esc(description)}"><link rel="manifest" href="/site.webmanifest"><link rel="icon" href="/assets/icons/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/assets/icons/icon-192.png"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" type="module"></script>${scripts.map(src=>`<script src="${src}" type="module"></script>`).join("")}</head><body class="${esc(bodyClass)}" data-page-path="${esc(path)}"><a class="skip-link" href="#main">Skip to content</a><div class="demo-banner" role="region" aria-label="Food and AI safety notice"><div class="shell">${icon("shield")}<span>Creative food concepts only. Allergens, nutrition and safe preparation are not verified.</span><a href="/safety/">Read the safety boundary</a></div></div>${header(path)}${main}${footer()}<dialog class="command-dialog" data-command-dialog aria-labelledby="command-title"><form method="dialog" class="dialog-surface"><div class="dialog-head"><div><p class="eyebrow">Quick navigation</p><h2 id="command-title">Jump to a workspace</h2></div><button class="icon-button" value="cancel" aria-label="Close quick navigation">${icon("close")}</button></div><label class="search-field"><span class="sr-only">Search pages</span>${icon("search")}<input type="search" data-command-input placeholder="Builder, board, journal…" autocomplete="off"></label><div class="command-results" data-command-results></div><p class="hint"><kbd>Ctrl</kbd>/<kbd>⌘</kbd> + <kbd>K</kbd></p></form></dialog><div class="toast-region" data-toast-region aria-live="polite"></div></body></html>`;
}
