import { readFile, readdir, stat } from "node:fs/promises";
import { extname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
const root=fileURLToPath(new URL("../",import.meta.url));const dist=join(root,"dist");
async function files(dir){const entries=await readdir(dir,{withFileTypes:true});const result=[];for(const entry of entries){const path=join(dir,entry.name);if(entry.isDirectory())result.push(...await files(path));else result.push(path);}return result;}
const all=await files(dist);const html=all.filter(path=>extname(path)===".html");const canonical=["index.html","builder/index.html","ideas/index.html","board/index.html","journal/index.html","about/index.html","safety/index.html","privacy/index.html","offline/index.html","404/index.html"];
let assertions=0;function check(value,message){assertions+=1;if(!value)throw new Error(message);}for(const rel of canonical)check(all.some(path=>relative(dist,path).replaceAll("\\","/")===rel),`Missing ${rel}`);check(html.length===11,`Expected 11 physical HTML files, found ${html.length}`);
const titles=new Set();for(const path of html){const source=await readFile(path,"utf8");const ids=[...source.matchAll(/ id="([^"]+)"/g)].map(match=>match[1]);check(new Set(ids).size===ids.length,`${relative(dist,path)} duplicate IDs`);check((source.match(/<main\b/g)||[]).length===1,`${relative(dist,path)} main count`);check((source.match(/<h1\b/g)||[]).length===1,`${relative(dist,path)} h1 count`);check(source.includes('name="description"'),`${relative(dist,path)} description`);check(source.includes('name="robots"'),`${relative(dist,path)} robots`);check(source.includes('class="skip-link"'),`${relative(dist,path)} skip link`);check(!/onclick=/i.test(source),`${relative(dist,path)} inline handler`);check(!/<script(?![^>]*src=)/i.test(source),`${relative(dist,path)} inline script`);const title=source.match(/<title>(.*?)<\/title>/)?.[1];check(Boolean(title),`${relative(dist,path)} title`);if(relative(dist,path)!=="404.html"){check(!titles.has(title),`Duplicate title ${title}`);titles.add(title);}}
const required=["site.webmanifest","sw.js","robots.txt","sitemap.xml",".well-known/security.txt","assets/site.css","assets/site.js","assets/app.js","assets/icons/favicon.svg","assets/icons/icon-192.png","assets/icons/icon-512.png"];for(const rel of required)check(all.some(path=>relative(dist,path).replaceAll("\\","/")===rel),`Missing ${rel}`);
const total=(await Promise.all(all.map(path=>stat(path)))).reduce((sum,value)=>sum+value.size,0);const js=(await Promise.all(all.filter(path=>[".js",".mjs"].includes(extname(path))).map(path=>stat(path)))).reduce((sum,value)=>sum+value.size,0);const css=(await stat(join(dist,"assets/site.css"))).size;check(total<=1_500_000,`Output ${total}`);check(js<=120_000,`JS ${js}`);check(css<=70_000,`CSS ${css}`);const sw=await readFile(join(dist,"sw.js"),"utf8");check(!sw.includes("__CACHE_VERSION__"),"Service worker version placeholder");check(!sw.includes("__PRECACHE__"),"Service worker precache placeholder");const precacheLine=sw.match(/const PRECACHE = (.*);/)?.[1]||"";check(!precacheLine.includes("/api/"),"Service worker must not precache API");const robots=await readFile(join(dist,"robots.txt"),"utf8");check(robots.includes("Disallow: /"),"Initial crawler denial");const sitemap=await readFile(join(dist,"sitemap.xml"),"utf8");check(!sitemap.includes("<url>"),"Initial sitemap must be empty");console.log(`${assertions} build assertions passed. ${html.length} HTML files, ${all.length} total files, ${total} bytes; browser/shared JavaScript ${js} bytes; CSS ${css} bytes.`);
